DROP TABLE IF EXISTS AWNSERS;
DROP TABLE IF EXISTS QUESTIONS;
DROP TABLE IF EXISTS TEST;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER(
    id INTEGER PRIMARY KEY ,
    name VARCHAR(100) NOT NULL,    
    pw VARCHAR(20) NOT NULL
);

CREATE TABLE TEST(
    id INTEGER PRIMARY KEY ,
    setBy INTEGER NOT NULL,
    timeSet TIMESTAMP
);

CREATE TABLE QUESTIONS(
    id INTEGER PRIMARY KEY,
    quesitonText VARCHAR(100) NOT NULL,
    awnser INTEGER,
    test INTEGER NOT NULL,
    FOREIGN KEY (test) REFERENCES TEST(id)
);

CREATE TABLE ATTEMPT(
    userID INTEGER NOT NULL,
    testID INTEGER NOT NULL,
    score INTEGER NOT NULL,
    timeCompleted TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USER(id),
    FOREIGN KEY (testID) REFERENCES TEST(id),
    PRIMARY KEY (UserID, testID)
);


